[gdrive]
type = drive
scope = drive
service_account_file = /config/rclone/your-project-service_account_file.json
root_folder_id =
team_drive =

[gdrive-shared]
type = alias
remote = gdrive,shared_with_me:rclone
